# Generated by Django 4.1.4 on 2022-12-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_doctor_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.calendar'),
        ),
    ]
