# Generated by Django 4.1.4 on 2022-12-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctor_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cabinet_number',
            field=models.IntegerField(),
        ),
    ]
