# Generated by Django 4.1.4 on 2022-12-14 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_doctor_cabinet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
